parameters:
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

jms_serializer:
    handlers:
        datetime:
            default_format: "d/m/Y"
            default_timezone: "UTC"