services:
    api.service.util.servico_base:
        abstract: true
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setFormFactory, ["@form.factory"]]
            - [setTokenStorage, ["@security.token_storage"]]
            - [setUserManager, ["@fos_user.user_manager"]]

    api.service.usuario:
        class: ApiRestBundle\Service\UserService
        parent: api.service.util.servico_base
        calls:
            - [setRepository, [UserBundle:User]]

    api.service.client:
        class: ApiRestBundle\Service\ClientService
        parent: api.service.util.servico_base
        calls:
            - [setRepository, [AppBundle:Client]]

    api.service.inscription:
        class: ApiRestBundle\Service\InscriptionService
        parent: api.service.util.servico_base
        calls:
            - [setRepository, [AppBundle:Inscription]]