<?php

namespace AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Adiciona filtros para selecionar apenas registros ativos à query.
     * @param QueryBuilder $qb Query inicial.
     * @return QueryBuilder Query com filtros.
     */
    public function addActiveQuery(QueryBuilder $qb = null) {
        $em = $this->getEntityManager();

        if (is_null($qb)) {
            $qb = $em->createQueryBuilder();
        }

        $qb->select(array('c'))
            ->from('AppBundle:Client', 'c');

        return $qb;
    }

    /**
    * Busca todas os registros de cliente para o relatório de acordo com o filtro
    * @param SearchReport $searchReport Entidade de busca para o report.
    * @return array Array de registros.
    */
    public function findForReport($searchReport){
      $qb = $this->addActiveQuery();

      if($searchReport->getBeginDate()!=null){
        $qb->andWhere('c.dtCreation >= :dt_creation')
        ->setParameter('dt_creation', $searchReport->getBeginDate()->setTime(00, 00, 00));
      }

      if($searchReport->getEndDate()!=null){
        $qb->andWhere('c.dtCreation <= :dt_creation2')
        ->setParameter('dt_creation2', $searchReport->getEndDate()->setTime(23, 59, 59));
      }

      $query = $qb->getQuery();

      return $query->getResult();
    }
}
