<?php

namespace AppBundle\Repository;

/**
 * InscriptionStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
