<?php

namespace AppBundle\Repository;

/**
 * InscriptionLessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionLessonRepository extends \Doctrine\ORM\EntityRepository
{
}
