<?php

namespace AppBundle\Repository;

/**
 * LessonFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonFilesRepository extends \Doctrine\ORM\EntityRepository
{
}
