<?php

namespace AppBundle\Repository;

/**
 * EbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametersConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
    public function addActiveQuery(QueryBuilder $qb = null) {
        $em = $this->getEntityManager();

        if (is_null($qb)) {
            $qb = $em->createQueryBuilder();
        }

        $qb->select(array('pc'))
            ->from('AppBundle:ParametersConfiguration', 'pc');

        return $qb;
    }

    public function getConfiguration()
    {
        $qb = $this->addActiveQuery();

        $qb->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
