<?php

namespace AppBundle\Repository;

use AppBundle\Entity\InscriptionStatus;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends \Doctrine\ORM\EntityRepository
{
    
}