<?php

namespace AppBundle\Repository;

/**
 * TestimonialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonialRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * Adiciona filtros para selecionar apenas registros ativos à query.
   * @param QueryBuilder $qb Query inicial.
   * @return QueryBuilder Query com filtros.
   */
  public function addActiveQuery(QueryBuilder $qb = null) {
      $em = $this->getEntityManager();

      if (is_null($qb)) {
          $qb = $em->createQueryBuilder();
      }

      $qb->select(array('t'))
          ->from('AppBundle:Testimonial', 't');

      return $qb;
  }

  public function findForHome($active = true, $max = 3)
  {
      $qb = $this->addActiveQuery();

      $qb->andWhere("t.active = :active")->setParameter("active", $active);

      $qb->setMaxResults($max);

      return $qb->getQuery()->getResult();
  }
}
