app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_user:
    resource: "@UserBundle/Controller/"
    type: annotation

api_rest:
    resource: "@ApiRestBundle/Resources/config/routing.yml"
    type: rest

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /settings/

fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"
    
user_logout:
    path:   /logout