# To get started with security, check out the documentation:
# https://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_PROFESSIONAL: ROLE_PROFESSIONAL
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_PROFESSIONAL, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        fos_facebook_provider:
            id: fos_facebook.user.login

    firewalls:
        main:
            # http_basic: ~
            pattern:      .*
            fos_facebook:
                app_url: "http://apps.facebook.com/vanbora"
                server_url: "http://dev.vanbora.com.br/"
                login_path:     /facebook/login
                check_path:     /facebook/login_check
                provider: fos_facebook_provider
                default_target_path: /
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    true
                check_path:     /login_check
                failure_path:   null
                use_referer:    true
                default_target_path: /
            logout:
                path:   /logout
                target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/, role: ROLE_SUPER_ADMIN }
        - { path: ^/backend, role: ROLE_SUPER_ADMIN }
        - { path: ^/dashboard/, role: ROLE_USER }
        - { path: ^/assinatura/, role: ROLE_USER }
